config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  ## Event categories
  scope 'events/categories', as: 'event_category' do
    get 'search', to: 'event_categories#search'
    get 'disabled', to: 'event_categories#disabled'
    get ':id/restore', to: 'event_categories#restore', as: 'restore'
  end
  resources :event_categories, path: 'events/categories'

  ## Events
  get 'events/search'
  get 'events/disabled'
  delete 'events/presence', to: 'event_presences#destroy'
  get 'events/:id/restore', to: 'events#restore'
  resources :events do
    get 'presence', to: 'event_presences#index'
    get 'presence/list', to: 'event_presences#list'
    post 'presence/create', to: 'event_presences#create'
  end

  ## Groups
  get 'groups/search'
  get 'groups/disabled'
  get 'groups/:id/restore', to: 'groups#restore'
  get 'groups/presence', to: 'group_presences#index'
  delete 'groups/presence', to: 'group_presences#destroy'
  resources :groups do
    get 'search_lists', to: 'groups#search_lists'
    get 'presence/new', to: 'group_presences#new'
    get 'presence/search', to: 'group_presences#search'
    post 'presence/create', to: 'group_presences#create'
    get 'presence/:list_id', to: 'group_presences#show'
    get 'active_members', to: 'groups#active_members'
  end

  ## Members
  get 'members/search'
  get 'members/disabled'
  resources :members do
    get 'restore', to: 'members#restore', as: 'restore'
    get 'activity', to: 'members#activity', as: 'activity'

    resources :recommendations
    resources :contracts
  end

  patch 'members/:member_id/recommendations', to: 'recommendations#update'

  ## Schools
  get 'schools/search'
  get 'schools/disabled'
  get 'schools/:id/restore', to: 'schools#restore'
  resources :schools

  ## Lesson subjects
  scope 'lessons/subjects', as: 'lesson_subject' do
    get 'search', to: 'lesson_subjects#search'
    get 'disabled', to: 'lesson_subjects#disabled'
    get ':id/restore', to: 'lesson_subjects#restore', as: 'restore'
  end
  resources :lesson_subjects, path: 'lessons/subjects'

  ## Lessons
  get 'lessons/search'
  resources :lessons

  # Consultations
  get 'consultations/disabled'
  get 'consultations/search'
  resources :consultations

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/consultation.rb
class Consultation < ApplicationRecord
  belongs_to :member

  validates_associated :member
  validates :description,
    allow_blank: true,
    length: { minimum: 3 }
  validates :datetime,
    presence: true
end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController
  def index
  end

  def new
    @consultation = Consultation.new
  end

  def search
    if (params[:since].present? &&
        params[:finish].present?)

      since = Time.at params[:since].to_i
      finish = Time.at params[:finish].to_i

      consultations = Consultation.active
        .includes(:member)
        .where(:datetime => since..finish)
        .order(datetime: :desc)
    else
      lessons = []
    end

    json = []
    consultations.each do |c|
      json.push({
          id: c.id,
          member: {
            first_name: c.member.first_name,
            last_name: c.member.last_name,
            phone: c.member.phone
          },
          datetime: c.datetime
        })
    end

    render json: json
  end

  def create
    consultation = Consultation.new consultation_params

    if consultation.save
      render json: {success: true}
    else
      render json: {
        success: false,
        errors: consultation.errors.full_messages
        }
    end
  end

  def show
    @consultation = Consultation.find_by_id params[:id]
    if @consultation.nil?
      render 'index'
    end
  end

  def edit
    @consultation = Consultation.find_or_create_by id: params[:id]

    @public_consultation = {
      id: @consultation.id,
      member: {
        id: @consultation.member.id,
        first_name: @consultation.member.first_name,
        last_name: @consultation.member.last_name,
        phone: @consultation.member.phone
      },
      datetime: @consultation.datetime,
      description: @consultation.description
    }
  end

  def update
    @consultation = Consultation.find params[:id]

    if @consultation.update consultation_params
      render json: {success: true}
    else
      render json: {
        success: false,
        errors: @consultation.errors.full_messages
        }
    end
  end

private
  def consultation_params
    params.permit :member_id, :datetime, :description
  end
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/views/consultations/_form.html.erb
<div class="form" ng-controller="ConsultationsFormCtrl"
  <% if @consultation.new_record? %>
    ng-init="setup()"
  <% else %>
    ng-init='set_data(<%= raw @public_consultation.to_json %>)'
  <% end %>
  >
  <p>
    <label><%= t "activerecord.attributes.consultation.member_id" %></label>
    <input type="text" ng-model="taking_member.first_name" readonly
      placeholder="<%= t "activerecord.attributes.member.first_name" %>" />
    <input type="text" ng-model="taking_member.last_name" readonly
      placeholder="<%= t "activerecord.attributes.member.last_name" %>" />
    <input type="text" ng-model="taking_member.phone" readonly
      placeholder="<%= t "activerecord.attributes.member.phone" %>" />
  </p>
  <p>
    <label><%= t "activerecord.attributes.consultation.datetime" %></label>
    <input type="datetime-local" ng-model="datetime" />
  </p>
  <p>
    <label><%= t "activerecord.attributes.consultation.description" %></label>
    <textarea ng-model="description"></textarea>
  </p>
  <p>
    <% if @consultation.new_record? %>
      <input type="button" ng-click="create()"
        value="<%= t "helpers.submit.consultation.create" %>" />
    <% else %>
      <input type="button" ng-click="update()"
        value="<%= t "helpers.submit.consultation.update" %>" />
    <% end %>
  </p>

  <div class="well search-block">
    <input type="text" ng-model="member.first_name"
    placeholder="<%= t "activerecord.attributes.member.first_name" %>" />
    <input type="text" ng-model="member.last_name"
      placeholder="<%= t "activerecord.attributes.member.last_name" %>" />
    <input type="text" ng-model="member.phone"
      placeholder="<%= t "activerecord.attributes.member.phone" %>" />

    <table class="table-list table-bordered table-striped">
      <thead>
        <tr>
          <th><%= t "activerecord.attributes.member.first_name" %></th>
          <th><%= t "activerecord.attributes.member.last_name" %></th>
          <th><%= t "activerecord.attributes.member.phone" %></th>
        </tr>
      </thead>
      <tbody>
        <tr ng-repeat="member in members">
          <td>{{ member.first_name }}</td>
          <td>{{ member.last_name }}</td>
          <td>{{ member.phone }}</td>
          <td><%= link_to t(:show), URI::unescape(member_path("{{ member.id }}")) %></td>
          <td>
            <a href="javascript:void(0)" ng-click="set_taking_member(member)" >
              <%= t :select %>
            </a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/consultations/disabled.html.erb
<h1>Consultations#disabled</h1>
<p>Find me in app/views/consultations/disabled.html.erb</p>

app/views/consultations/edit.html.erb
<h2><%= @title = t :edit_consultation %></h2>
<%= link_to t(:back), consultations_path %>
<%= link_to t(:show), consultation_path(@consultation) %>
<%= render 'form' %>

app/views/consultations/index.html.erb
<h1><%= @title = t :consultations_list %></h1>

<%= link_to t(:adding_consultation), new_consultation_path %>

<div ng-controller="ConsultationsIndexCtrl">

  <h3><%= t :searching %></h3>
  <div class="well search-block">
    <div class="inline-block">
      <label><%= t :since %></label>
      <input type="datetime-local" ng-model="since" />
    </div>
    <div class="inline-block">
      <label><%= t :pending %></label>
      <input type="datetime-local" ng-model="finish" />
    </div>
  </div>

  <table class="table-list table-bordered table-striped">
    <thead>
      <tr>
        <th><%= t "activerecord.attributes.consultation.member_id" %></th>
        <th><%= t "activerecord.attributes.consultation.datetime" %></th>
      </tr>
    </thead>
    <tbody>
      <tr ng-repeat="c in consultations">
        <td>
          {{ c.member.first_name }}
          {{ c.member.last_name }}
          {{ c.member.phone }}
        </td>
        <td>
          <datetime value="{{ c.datetime }}" />
        </td>
        <td><%= link_to t(:show), URI::unescape(consultation_path("{{ c.id }}")) %></td>
        <td><%= link_to t(:edit), URI::unescape(edit_consultation_path("{{ c.id }}")) %></td>
        <td><%= link_to t(:destroy), URI::unescape(consultation_path("{{ c.id }}")),
                method: :delete,
                data: { confirm: t(:are_you_sure) } %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/consultations/new.html.erb
<h2><%= @title = t :adding_consultation %></h2>
<%= link_to t(:back), consultations_path %>
<%= render 'form' %>

app/views/consultations/show.html.erb
<h2><%= @title = t "activerecord.models.consultation" %></h2>

<%= link_to t(:back), consultations_path %>
<%= link_to t(:adding_consultation), new_consultation_path %>
<%= link_to t(:edit_consultation), edit_consultation_path(@consultation) %>

<p>
    <%= t "activerecord.attributes.consultation.member_id" %>:
    <%= @consultation.member.first_name %>
    <%= @consultation.member.last_name %>
    <%= @consultation.member.phone %>
    <%= link_to t(:show), member_path(@consultation.member) %>
</p>
<p>
    <%= t "activerecord.attributes.consultation.datetime" %>:
    <datetime value="<%= @consultation.datetime %>" />
</p>
<p>
    <%= t "activerecord.attributes.consultation.description" %>:
    <pre><%= @consultation.description %></pre>
</p>