config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  ## Event categories
  scope 'events/categories', as: 'event_category' do
    get 'search', to: 'event_categories#search'
    get 'disabled', to: 'event_categories#disabled'
    get ':id/restore', to: 'event_categories#restore', as: 'restore'
  end
  resources :event_categories, path: 'events/categories'

  ## Events
  get 'events/search'
  get 'events/disabled'
  delete 'events/presence', to: 'event_presences#destroy'
  get 'events/:id/restore', to: 'events#restore'
  resources :events do
    get 'presence', to: 'event_presences#index'
    get 'presence/list', to: 'event_presences#list'
    post 'presence/create', to: 'event_presences#create'
  end

  ## Groups
  get 'groups/search'
  get 'groups/disabled'
  get 'groups/:id/restore', to: 'groups#restore'
  get 'groups/presence', to: 'group_presences#index'
  delete 'groups/presence', to: 'group_presences#destroy'
  resources :groups do
    get 'search_lists', to: 'groups#search_lists'
    get 'presence/new', to: 'group_presences#new'
    get 'presence/search', to: 'group_presences#search'
    post 'presence/create', to: 'group_presences#create'
    get 'presence/:list_id', to: 'group_presences#show'
    get 'active_members', to: 'groups#active_members'
  end

  ## Members
  get 'members/search'
  get 'members/disabled'
  resources :members do
    get 'restore', to: 'members#restore', as: 'restore'
    get 'activity', to: 'members#activity', as: 'activity'

    resources :recommendations
    resources :contracts
  end

  patch 'members/:member_id/recommendations', to: 'recommendations#update'

  ## Schools
  get 'schools/search'
  get 'schools/disabled'
  get 'schools/:id/restore', to: 'schools#restore'
  resources :schools

  ## Lesson subjects
  scope 'lessons/subjects', as: 'lesson_subject' do
    get 'search', to: 'lesson_subjects#search'
    get 'disabled', to: 'lesson_subjects#disabled'
    get ':id/restore', to: 'lesson_subjects#restore', as: 'restore'
  end
  resources :lesson_subjects, path: 'lessons/subjects'

  ## Lessons
  get 'lessons/search'
  resources :lessons

  # Consultations
  get 'consultations/disabled'
  get 'consultations/search'
  resources :consultations

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_presences

  validates :name,
    presence: true,
    length: { minimum: 3 }

  validates :time,
    presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
  end

  def search
    if params[:id].present?
      groups = Group.active.where id: params[:id]
    elsif params[:name].present?
      groups = Group.active.where "name LIKE ?", "%#{params[:name]}%"
    else
      groups = Group.active
    end

    render json: groups
  end

  def search_lists
    if params[:since].present? && params[:finish].present?
      since = Time.at(params[:since].to_f)
      finish = Time.at(params[:finish].to_f)

      group_lists = GroupPresence.active
        .select(:datetime)
        .where(group_id: params[:group_id])
        .where(:datetime => since..finish)
        .group(:datetime)
        .order(datetime: :desc)
        .count(:member_id)
    else
      group_lists = []
    end

    render json: group_lists.map { |key, value| {"datetime": key, "count": value} }
  end

  def active_members
    since = params[:since]
    finish = params[:finish]

    tmp = GroupPresence.active
      .select(:member_id)
      .group(:member_id)
      .where(:datetime => since..finish)
      .count(:member_id)

    member_ids = []
    tmp.each do |id, count|
      if count >= params[:min_attendece].to_i
        member_ids.push id
      end
    end

    members = Member.active
      .select(:id, :first_name, :last_name, :phone, :pesel)
      .where(:id => member_ids)

    render json: members
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new group_params

    if @group.save
      redirect_to @group
    else
      render 'new'
    end
  end

  def show
    @group = Group.find params[:id]
  end

  def edit
    @group = Group.find_or_create_by id: params[:id]
  end

  def update
    @group = Group.find params[:id]

    if @group.update group_params
      redirect_to @group
    else
      render 'edit'
    end
  end

  def destroy
    @group = Group.find params[:id]
    @group.active = false
    @group.save

    redirect_to groups_path
  end

  def disabled
    @groups = Group.disabled
  end

  def restore
    @group = Group.find params[:id]
    @group.active = true
    @group.save

    redirect_to @group
  end

private
  def group_params
    params.require(:group).permit :name, :description, :time
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_active_members.html.erb
<div ng-controller="GroupActiveMembersCtrl"
  ng-init="group_id=<%= params[:id] %>">
  <div class="well search-block">
    <label>
      <%= t :min_attendance %>
      <input type="number" ng-model="search.min_attendece" style="width: 50px;">
    </label>
    <label>
      <%= t :since %>
      <input type="datetime-local" ng-model="search.since" />
    </label>
    <label>
      <%= t :pending %>
      <input type="datetime-local" ng-model="search.finish" />
    </label>
  </div>

  <table class="table-list table-bordered table-striped">
    <thead>
      <tr>
        <th><%= t "activerecord.attributes.member.first_name" %></th>
        <th><%= t "activerecord.attributes.member.last_name" %></th>
        <th><%= t "activerecord.attributes.member.phone" %></th>
        <th><%= t "activerecord.attributes.member.pesel" %></th>
      </tr>
    </thead>
    <tbody>
      <tr ng-repeat="member in members">
        <td>{{ member.first_name }}</td>
        <td>{{ member.last_name }}</td>
        <td>{{ member.phone }}</td>
        <td>{{ member.pesel }}</td>
        <td><%= link_to t(:show), URI::unescape(member_path("{{ member.id }}")) %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= t :error, count: @group.errors.count %>
      </h2>
      <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :time %><br>
    <%= f.time_field :time %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/groups/_show_lists.html.erb
<div ng-controller="GroupsShowListsCtrl">
  <input type="hidden" ng-init="group_id=<%= @group.id %>" />
  <div class="alert alert-danger" ng-repeat="error in errors">
    {{ error }}
  </div>
  <div class="well search-block">
    <label><%= t :since %></label>
    <input type="datetime-local" ng-model="since" />
    <label><%= t :pending %></label>
    <input type="datetime-local" ng-model="finish" />
  </div>

  <table class="table-list table-bordered table-striped">
    <thead>
      <tr>
        <th><%= t "activerecord.attributes.group_presence.datetime" %></th>
        <th><%= t :members_count %></th>
      </tr>
    </thead>
    <tbody>
      <tr ng-repeat="l in lists">
        <td><datetime value="{{ l.datetime }}" /></td>
        <td>{{ l.count }}</td>
        <td><a href="<%= params[:id] %>/presence/{{ list_id(l) }}"><%= t :show %></a></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/groups/disabled.html.erb
<% @title = t :disabled_groups %>
<h1><%= t :disabled_groups %></h1>

<%= link_to t(:groups_list), groups_path %>
<table class="table-list table-bordered table-striped">
  <tr>
    <th><%= t "activerecord.attributes.group.name" %></th>
  </tr>

  <% @groups.each do |group| %>
    <tr>
      <td><%= group.name %></td>
      <td><%= link_to t(:restore), controller: "groups", action: "restore", id: group %></td>
    </tr>
  <% end %>
</table>

app/views/groups/edit.html.erb
<h1><%= @title = t :edit_group %></h1>
<%= render 'form' %>
<%= link_to t(:back), groups_path %>

app/views/groups/index.html.erb
<h1><%= @title = t :groups_list %></h1>

<%= link_to t(:adding_group), new_group_path %> | 
<%= link_to t(:disabled_groups), controller: "groups", action: "disabled" %>

<div ng-controller="GroupsCtrl">

  <h3><%= t :searching %></h3>
  <div class="well search-block">
    <input type="text" ng-model="search_name"
      placeholder="<%= t "activerecord.attributes.group.name" %>" />
  </div>

  <table class="table-list table-bordered table-striped">
    <thead>
      <tr>
        <th><%= t "activerecord.attributes.group.name" %></th>
      </tr>
    </thead>
    <tbody>
      <tr ng-repeat="group in groups">
        <td>{{ group.name }}</td>
        <td><%= link_to t(:show), URI::unescape(group_path("{{ group.id }}")) %></td>
        <td><%= link_to t(:add_presence), URI::unescape(group_presence_new_path("{{ group.id }}")) %></td>
        <td><%= link_to t(:edit), URI::unescape(edit_group_path("{{ group.id }}")) %></td>
        <td><%= link_to t(:destroy), URI::unescape(group_path("{{ group.id }}")),
                method: :delete,
                data: { confirm: t(:are_you_sure) } %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<% @title = t :adding_group %>
<h2><%= t :adding_group %></h2>
<%= render 'form' %>
<%= link_to t(:back), groups_path %>

app/views/groups/show.html.erb
<% @title = t("activerecord.models.group") + ": " + @group.name %>

<h2><%= t "activerecord.models.group" %></h2>
<%= link_to t(:back), groups_path %> |
<%= link_to t(:edit_group), edit_group_path(@group) %> |
<%= link_to t(:add_presence), group_presence_new_path(@group) %> |
<%= link_to t(:add_group), new_group_path %>

<p>
    <%= t "activerecord.attributes.group.name" %>:
    <%= @group.name %>
</p>
<p>
    <%= t "activerecord.attributes.group.time" %>:
    <time value="<%= @group.time %>" />
</p>
<p>
    <%= t "activerecord.attributes.group.description" %>:
    <pre><%= @group.description %></pre>
</p>


<%= hideable t(:presences_lists), render("show_lists") %>
<%= hideable t(:active_members), render("active_members") %>