config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  ## Event categories
  scope 'events/categories', as: 'event_category' do
    get 'search', to: 'event_categories#search'
    get 'disabled', to: 'event_categories#disabled'
    get ':id/restore', to: 'event_categories#restore', as: 'restore'
  end
  resources :event_categories, path: 'events/categories'

  ## Events
  get 'events/search'
  get 'events/disabled'
  delete 'events/presence', to: 'event_presences#destroy'
  get 'events/:id/restore', to: 'events#restore'
  resources :events do
    get 'presence', to: 'event_presences#index'
    get 'presence/list', to: 'event_presences#list'
    post 'presence/create', to: 'event_presences#create'
  end

  ## Groups
  get 'groups/search'
  get 'groups/disabled'
  get 'groups/:id/restore', to: 'groups#restore'
  get 'groups/presence', to: 'group_presences#index'
  delete 'groups/presence', to: 'group_presences#destroy'
  resources :groups do
    get 'search_lists', to: 'groups#search_lists'
    get 'presence/new', to: 'group_presences#new'
    get 'presence/search', to: 'group_presences#search'
    post 'presence/create', to: 'group_presences#create'
    get 'presence/:list_id', to: 'group_presences#show'
    get 'active_members', to: 'groups#active_members'
  end

  ## Members
  get 'members/search'
  get 'members/disabled'
  resources :members do
    get 'restore', to: 'members#restore', as: 'restore'
    get 'activity', to: 'members#activity', as: 'activity'

    resources :recommendations
    resources :contracts
  end

  patch 'members/:member_id/recommendations', to: 'recommendations#update'

  ## Schools
  get 'schools/search'
  get 'schools/disabled'
  get 'schools/:id/restore', to: 'schools#restore'
  resources :schools

  ## Lesson subjects
  scope 'lessons/subjects', as: 'lesson_subject' do
    get 'search', to: 'lesson_subjects#search'
    get 'disabled', to: 'lesson_subjects#disabled'
    get ':id/restore', to: 'lesson_subjects#restore', as: 'restore'
  end
  resources :lesson_subjects, path: 'lessons/subjects'

  ## Lessons
  get 'lessons/search'
  resources :lessons

  # Consultations
  get 'consultations/disabled'
  get 'consultations/search'
  resources :consultations

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_presences

  belongs_to :event_category

  validates :name,
    presence: true,
    length: { minimum: 3 }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  end

  def search
    if params[:id].present?
      events = Event.active
        .includes(:event_category)
        .select(:id, :name, :event_category_id, :datetime)
        .where(id: params[:id])
    elsif params[:name].present? && params[:event_category_id].present?
      events = Event.active
        .includes(:event_category)
        .select(:id, :name, :event_category_id, :datetime)
        .where("name LIKE ?", "%#{params[:name]}%")
        .where(event_category_id: params[:event_category_id])
    elsif params[:name].present?
      events = Event.active
        .includes(:event_category)
        .select(:id, :name, :event_category_id, :datetime)
        .where("name LIKE ?", "%#{params[:name]}%")
    elsif params[:event_category_id].present?
      events = Event.active
        .includes(:event_category)
        .select(:id, :name, :event_category_id, :datetime)
        .where(event_category_id: params[:event_category_id])
    else
      events = Event.active
        .includes(:event_category)
        .select(:id, :name, :event_category_id, :datetime)
    end

    json_enevts = []
    events.each do |event|
      json_enevts.push(
        id: event.id,
        name: event.name,
        category: event.event_category.name,
        datetime: event.datetime
      )
    end

    render json: json_enevts
  end

  def new
    @event = Event.new
    @event.datetime = Time.now
  end

  def create
    @event = Event.new event_params

    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    @event = Event.find_by_id params[:id]
    if @event.nil?
      render 'index'
    end
  end

  def edit
    @event = Event.find_or_create_by id: params[:id]
  end

  def update
    @event = Event.find params[:id]

    if @event.update event_params
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find params[:id]
    @event.active = false
    @event.save

    redirect_to events_path
  end

  def disabled
    @events = Event.disabled
  end

  def restore
    @event = Event.find params[:id]
    @event.active = true
    @event.save

    redirect_to @event
  end

private
  def event_params
    params.require(:event).permit :name, :description, :event_category_id,
      :datetime
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= t :error, count: @event.errors.count %>
      </h2>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :event_category_id %><br>
    <%= f.collection_select :event_category_id, EventCategory.active, :id, :name %>
  </p>
  <p>
    <%= f.label :datetime %><br>
    <%= f.datetime_local_field :datetime %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/events/disabled.html.erb
<% @title = t :disabled_events %>
<h1><%= t :disabled_events %></h1>

<%= link_to t(:events_list), events_path %>
<table class="table-list table-bordered table-striped">
  <tr>
    <th><%= t "activerecord.attributes.event.name" %></th>
  </tr>

  <% @events.each do |event| %>
    <tr>
      <td><%= event.name %></td>
      <td><%= link_to t(:restore), controller: "events", action: "restore", id: event %></td>
    </tr>
  <% end %>
</table>

app/views/events/edit.html.erb
<h1><%= @title = t :edit_event %></h1>
<%= link_to t(:back), events_path %>
<%= render 'form' %>

app/views/events/index.html.erb
<% @title = t :events_list %>
<h1><%= t :events_list %></h1>

<%= link_to t(:adding_event), new_event_path %>
<%= link_to t(:disabled_events), controller: "events", action: "disabled" %>

<div ng-controller="EventsCtrl">
  <h3><%= t :searching %></h3>
  <div class="well search-block">
    <div class="inline-block">
      <input type="text" ng-model="event.name"
        placeholder="<%= t "activerecord.attributes.event.name" %>" />
    </div>
    <div class="inline-block">
      <label><%= t "activerecord.attributes.event.event_category_id" %></label>
      <select ng-model="event.event_category_id">
        <option value=""><%= t "helpers.select.prompt" %></option>
        <% EventCategory.active.each do |c| %>
        <option value="<%= c.id %>"><%= c.name %></option>
        <% end %>
      </select>
    </div>
  </div>

  <table class="table-list table-bordered table-striped">
    <thead>
      <tr>
        <th><%= t "activerecord.attributes.event.name" %></th>
        <th><%= t "activerecord.attributes.event.event_category_id" %></th>
        <th><%= t "activerecord.attributes.event.datetime" %></th>
      </tr>
    </thead>
    <tbody>
      <tr ng-repeat="event in events">
        <td>{{ event.name }}</td>
        <td>{{ event.category }}</td>
        <td><datetime value="{{ event.datetime }}" /></td>
        <td><%= link_to t(:show), URI::unescape(event_path("{{ event.id }}")) %></td>
        <td><%= link_to t(:edit), URI::unescape(edit_event_path("{{ event.id }}")) %></td>
        <td><%= link_to t(:presences_list), URI::unescape(event_presence_path("{{ event.id }}")) %></td>
        <td><%= link_to t(:destroy), URI::unescape(event_path("{{ event.id }}")),
                  method: :delete,
                  data: { confirm: t(:are_you_sure) } %></td>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/events/new.html.erb
<h2><%= @title = t :adding_event %></h2>

<%= link_to t(:back), events_path %>

<%= render 'form' %>

app/views/events/show.html.erb
<% @title = t("activerecord.models.event") + ": " + @event.name %>
<h2><%= t "activerecord.models.event" %></h2>

<%= link_to t(:back), events_path %>
<%= link_to t(:edit_event), edit_event_path(@event) %>
<%= link_to t(:presences_list), event_presence_path(@event) %>
<%= link_to t(:add_event), new_event_path %>

<p>
    <%= t "activerecord.attributes.event.name" %>:
    <%= @event.name %>
</p>
<p>
    <%= t "activerecord.attributes.event.event_category_id" %>:
    <%= @event.event_category.name %>
</p>
<p>
    <%= t "activerecord.attributes.event.datetime" %>:
    <datetime value="<%= @event.datetime %>" />
</p>
<p>
    <%= t "activerecord.attributes.event.description" %>:
    <pre><%= @event.description %></pre>
</p>