config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  ## Event categories
  scope 'events/categories', as: 'event_category' do
    get 'search', to: 'event_categories#search'
    get 'disabled', to: 'event_categories#disabled'
    get ':id/restore', to: 'event_categories#restore', as: 'restore'
  end
  resources :event_categories, path: 'events/categories'

  ## Events
  get 'events/search'
  get 'events/disabled'
  delete 'events/presence', to: 'event_presences#destroy'
  get 'events/:id/restore', to: 'events#restore'
  resources :events do
    get 'presence', to: 'event_presences#index'
    get 'presence/list', to: 'event_presences#list'
    post 'presence/create', to: 'event_presences#create'
  end

  ## Groups
  get 'groups/search'
  get 'groups/disabled'
  get 'groups/:id/restore', to: 'groups#restore'
  get 'groups/presence', to: 'group_presences#index'
  delete 'groups/presence', to: 'group_presences#destroy'
  resources :groups do
    get 'search_lists', to: 'groups#search_lists'
    get 'presence/new', to: 'group_presences#new'
    get 'presence/search', to: 'group_presences#search'
    post 'presence/create', to: 'group_presences#create'
    get 'presence/:list_id', to: 'group_presences#show'
    get 'active_members', to: 'groups#active_members'
  end

  ## Members
  get 'members/search'
  get 'members/disabled'
  resources :members do
    get 'restore', to: 'members#restore', as: 'restore'
    get 'activity', to: 'members#activity', as: 'activity'

    resources :recommendations
    resources :contracts
  end

  patch 'members/:member_id/recommendations', to: 'recommendations#update'

  ## Schools
  get 'schools/search'
  get 'schools/disabled'
  get 'schools/:id/restore', to: 'schools#restore'
  resources :schools

  ## Lesson subjects
  scope 'lessons/subjects', as: 'lesson_subject' do
    get 'search', to: 'lesson_subjects#search'
    get 'disabled', to: 'lesson_subjects#disabled'
    get ':id/restore', to: 'lesson_subjects#restore', as: 'restore'
  end
  resources :lesson_subjects, path: 'lessons/subjects'

  ## Lessons
  get 'lessons/search'
  resources :lessons

  # Consultations
  get 'consultations/disabled'
  get 'consultations/search'
  resources :consultations

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :lesson_subject
  belongs_to :giving_member,
    class_name: 'Member',
    foreign_key: 'giving_member_id'
  belongs_to :taking_member,
    class_name: 'Member',
    foreign_key: 'taking_member_id'

  validates_associated :giving_member
  validates_associated :taking_member
  validates_associated :lesson_subject
  
  validates :time,
    presence: true
  validates :datetime,
    presence: true
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
  end

  def new
    @lesson = Lesson.new
  end

  def search
    if (params[:lesson_subject_id].present? &&
        params[:since].present? &&
        params[:finish].present?)

      since = Time.at params[:since].to_i
      finish = Time.at params[:finish].to_i

      lessons = Lesson.active
        .includes(:giving_member, :taking_member, :lesson_subject)
        .where(:datetime => since..finish)
        .where(lesson_subject_id: params[:lesson_subject_id])
        .order(datetime: :desc)
    elsif params[:since].present? && params[:finish].present?
      since = Time.at params[:since].to_i
      finish = Time.at params[:finish].to_i

      lessons = Lesson.active
        .includes(:giving_member, :taking_member, :lesson_subject)
        .where(:datetime => since..finish)
        .order(datetime: :desc)
    else
      lessons = []
    end

    json = []
    lessons.each do |l|
      json.push({
          id: l.id,
          giving_member: {
            full_name: l.giving_member.full_name,
            pesel: l.giving_member.pesel
          },
          taking_member: {
            full_name: l.taking_member.full_name,
            pesel: l.taking_member.pesel
          },
          lesson_subject: l.lesson_subject.name,
          datetime: l.datetime
        })
    end

    render json: json
  end

  def create
    lesson = Lesson.new lesson_params

    if lesson.save
      render json: {success: true}
    else
      render json: {
        success: false,
        errors: lesson.errors.full_messages
        }
    end
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def edit
    @lesson = Lesson.find_or_create_by id: params[:id]

    lesson_subjects = LessonSubject.active.select(:id, :name)

    @public_lesson = {
      id: @lesson.id,
      giving_member: {
        id: @lesson.giving_member.id,
        first_name: @lesson.giving_member.first_name,
        last_name: @lesson.giving_member.last_name,
        pesel: @lesson.giving_member.pesel
      },
      taking_member: {
        id: @lesson.taking_member.id,
        first_name: @lesson.taking_member.first_name,
        last_name: @lesson.taking_member.last_name,
        pesel: @lesson.taking_member.pesel
      },
      lesson_subjects: lesson_subjects,
      lesson_subject: {
        id: @lesson.lesson_subject.id,
        name: @lesson.lesson_subject.name
      },
      time: @lesson.time,
      datetime: @lesson.datetime
    }
  end

  def update
    @lesson = Lesson.find params[:id]

    if @lesson.update lesson_params
      render json: {success: true}
    else
      render json: {
        success: false,
        errors: @lesson.errors.full_messages
        }
    end
  end

  def destroy
    lesson = Lesson.find params[:id]
    lesson.destroy
    redirect_to lessons_path
  end

private
  def lesson_params
    params.permit :giving_member_id, :taking_member_id, :lesson_subject_id,
      :time, :datetime
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<div class="form" ng-controller="LessonFormCtrl"
  <% if @lesson.new_record? %>
    ng-init="setup()"
  <% else %>
    ng-init='set_data(<%= raw @public_lesson.to_json %>)'
  <% end %>
  >
  <table>
    <tr>
      <td>
        <label><%= t "activerecord.attributes.lesson.giving_member_id" %></label>
      </td>
      <td>
        <input type="text" ng-model="giving_member.first_name" readonly
          placeholder="<%= t "activerecord.attributes.member.first_name" %>" />
      </td>
      <td>
        <input type="text" ng-model="giving_member.last_name" readonly
          placeholder="<%= t "activerecord.attributes.member.last_name" %>" />
      </td>
      <td>
        <input type="text" ng-model="giving_member.pesel" readonly
          placeholder="<%= t "activerecord.attributes.member.pesel" %>" />
      </td>
    </tr>
    <tr>
      <td>
        <label><%= t "activerecord.attributes.lesson.taking_member_id" %></label>
      </td>
      <td>
        <input type="text" ng-model="taking_member.first_name" readonly
          placeholder="<%= t "activerecord.attributes.member.first_name" %>" />
      </td>
      <td>
        <input type="text" ng-model="taking_member.last_name" readonly
          placeholder="<%= t "activerecord.attributes.member.last_name" %>" />
      </td>
      <td>
        <input type="text" ng-model="taking_member.pesel" readonly
          placeholder="<%= t "activerecord.attributes.member.pesel" %>" />
      </td>
    </tr>
  </table>
  <div class="inline-block">
    <label><%= t "activerecord.attributes.lesson.lesson_subject_id" %></label>
    <% if @lesson.new_record? %>
      <select ng-model="lesson_subject_id">
        <option value=""><%= t "helpers.select.prompt" %></option>
        <% LessonSubject.active.select(:id, :name).each do |ls| %>
          <option value="<%= ls.id %>"><%= ls.name %></option>
        <% end %>
      </select>
    <% else %>
      <select
        ng-model="lesson_subject_id"
        ng-options="lesson_subject.name for lesson_subject in lesson_subjects">
      </select>
    <% end %>
  </div>

  <div class="inline-block">
    <label><%= t "activerecord.attributes.lesson.datetime" %></label>
    <input type="datetime-local" ng-model="datetime" />
  </div>

  <div class="inline-block">
    <label><%= t "activerecord.attributes.lesson.time" %></label>
    <input type="time" ng-model="time" />
  </div>

  <p>
    <% if @lesson.new_record? %>
      <input type="button" ng-click="create()"
        value="<%= t "helpers.submit.lesson.create" %>" />
    <% else %>
      <input type="button" ng-click="update()"
        value="<%= t "helpers.submit.lesson.update" %>" />
    <% end %>
  </p>

  <div class="well search-block">
    <input type="text" ng-model="member.first_name"
    placeholder="<%= t "activerecord.attributes.member.first_name" %>" />
    <input type="text" ng-model="member.last_name"
      placeholder="<%= t "activerecord.attributes.member.last_name" %>" />
    <input type="text" ng-model="member.pesel"
      placeholder="<%= t "activerecord.attributes.member.pesel" %>" />

    <table class="table-list table-bordered table-striped">
      <thead>
        <tr>
          <th><%= t "activerecord.attributes.member.first_name" %></th>
          <th><%= t "activerecord.attributes.member.last_name" %></th>
          <th><%= t "activerecord.attributes.member.pesel" %></th>
        </tr>
      </thead>
      <tbody>
        <tr ng-repeat="member in members">
          <td>{{ member.first_name }}</td>
          <td>{{ member.last_name }}</td>
          <td>{{ member.pesel }}</td>
          <td><%= link_to t(:show), URI::unescape(member_path("{{ member.id }}")) %></td>
          <td>
            <a href="javascript:void(0)" ng-click="set_giving_member(member)" >
              <%= t "activerecord.attributes.lesson.giving_member_id" %>
            </a>
          </td>
          <td>
            <a href="javascript:void(0)" ng-click="set_taking_member(member)" >
              <%= t "activerecord.attributes.lesson.taking_member_id" %>
            </a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/lessons/edit.html.erb
<h2><%= @title = t :edit_lesson %></h2>
<%= link_to t(:back), lessons_path %> | 
<%= link_to t(:show), lesson_path(@lesson) %>
<%= render 'form' %>

app/views/lessons/index.html.erb
<h1><%= @title = t :lessons %></h1>

<%= link_to t(:adding_lesson), new_lesson_path %>

<div ng-controller="LessonsIndexCtrl">

  <h3><%= t :searching %></h3>
  <div class="well search-block">
    <div class="inline-block">
      <label><%= t "activerecord.attributes.lesson.lesson_subject_id" %></label>
      <select ng-model="lesson_subject_id">
        <option value=""><%= t "helpers.select.prompt" %></option>
        <% LessonSubject.active.each do |ls| %>
        <option value="<%= ls.id %>"><%= ls.name %></option>
        <% end %>
      </select>
    </div>
    <div class="inline-block">
      <label><%= t :since %></label>
      <input type="datetime-local" ng-model="since" />
    </div>
    <div class="inline-block">
      <label><%= t :pending %></label>
      <input type="datetime-local" ng-model="finish" />
    </div>
  </div>

  <table class="table-list table-bordered table-striped">
    <thead>
      <tr>
        <th><%= t "activerecord.attributes.lesson.giving_member_id" %></th>
        <th><%= t "activerecord.attributes.lesson.taking_member_id" %></th>
        <th><%= t "activerecord.attributes.lesson.lesson_subject_id" %></th>
        <th><%= t "activerecord.attributes.lesson.datetime" %></th>
      </tr>
    </thead>
    <tbody>
      <tr ng-repeat="l in lessons">
        <td>
          {{ l.giving_member.full_name }}
          {{ l.giving_member.pesel }}
        </td>
        <td>
          {{ l.taking_member.full_name }}
          {{ l.taking_member.pesel }}
        </td>
        <td>
          {{ l.lesson_subject }}
        </td>
        <td>
          <datetime value="{{ l.datetime }}" />
        </td>
        <td><%= link_to t(:show), URI::unescape(lesson_path("{{ l.id }}")) %></td>
        <td><%= link_to t(:edit), URI::unescape(edit_lesson_path("{{ l.id }}")) %></td>
        <td><%= link_to t(:destroy), URI::unescape(lesson_path("{{ l.id }}")),
                method: :delete,
                data: { confirm: t(:are_you_sure) } %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/lessons/new.html.erb
<div class="lesson">
  <h1><%= @title = t :adding_lesson %></h1>
  <%= link_to t(:back), lessons_path %>

  <%= render 'form' %>
</div>

app/views/lessons/show.html.erb
<h2><%= @title = t "activerecord.models.lesson" %></h2>

<%= link_to t(:back), lessons_path %>
<%= link_to t(:adding_lesson), new_lesson_path %>
<%= link_to t(:edit_lesson), edit_lesson_path(@lesson) %>

<p>
    <%= t "activerecord.attributes.lesson.giving_member_id" %>:
    <%= @lesson.giving_member.full_name %>
    <%= @lesson.giving_member.pesel %>
    <%= link_to t(:show), member_path(@lesson.giving_member) %>
</p>
<p>
    <%= t "activerecord.attributes.lesson.taking_member_id" %>:
    <%= @lesson.taking_member.full_name %>
    <%= @lesson.taking_member.pesel %>
    <%= link_to t(:show), member_path(@lesson.taking_member) %>
</p>
<p>
    <%= t "activerecord.attributes.lesson.lesson_subject_id" %>:
    <%= @lesson.lesson_subject.name %>
</p>
<p>
    <%= t "activerecord.attributes.lesson.datetime" %>:
    <datetime value="<%= @lesson.datetime %>"></datetime>
</p>
<p>
    <%= t "activerecord.attributes.lesson.time" %>:
    <time value="<%= @lesson.time %>"></time>
</p>